# Generated by Django 5.0.6 on 2024-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('group_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_credit', models.BooleanField(blank=True, default=False)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('bill_day', models.DateTimeField(blank=True)),
                ('repayment_day', models.DateTimeField(blank=True)),
                ('is_total_asset', models.BooleanField(blank=True, default=True)),
                ('is_no_budget', models.BooleanField(blank=True, default=False)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
