# Generated by Django 5.0.6 on 2024-08-01 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetgroup_asset_name_alter_asset_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetgroup',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='group_name',
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.assetgroup'),
        ),
    ]
