# Generated by Django 5.0.6 on 2024-08-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_rename_group_name_assetgroup_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='bill_day',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='repayment_day',
        ),
    ]
