# Generated by Django 5.0.6 on 2024-08-02 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_asset_bill_day_asset_repayment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='asset.assetgroup'),
        ),
    ]
