# Generated by Django 5.0.6 on 2024-08-02 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_asset_group'),
        ('book', '0002_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroup',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='book.book'),
        ),
    ]
