# Generated by Django 5.0.6 on 2024-08-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_alter_asset_group_alter_assetgroup_book'),
        ('book', '0003_book_monthly_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset.assetgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='book.book'),
        ),
    ]
