# Generated by Django 5.0.6 on 2024-08-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='monthly_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
