# Generated by Django 5.0.6 on 2024-08-03 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_user'),
        ('record', '0005_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='author',
        ),
        migrations.AddField(
            model_name='record',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book'),
        ),
    ]
