# Generated by Django 5.0.6 on 2024-08-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_marked_tax_return',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
