# Generated by Django 5.0.6 on 2024-08-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_alter_asset_group_alter_assetgroup_book'),
        ('book', '0003_book_monthly_goal'),
        ('record', '0009_record_is_marked_tax_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_asset', to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_asset', to='asset.asset'),
        ),
    ]
