# Generated by Django 5.1 on 2024-12-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0011_scheduledrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledrecord",
            name="week_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of weekdays (0-6) for weekly schedules, where Monday is 0 and Sunday is 6",
            ),
        ),
    ]
