# Generated by Django 5.1 on 2024-12-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_alter_scheduledrecord_week_days'),
        ('record', '0012_scheduledrecord_num_of_days_and_more'),
    ]

    operations = [
    ]
