# Generated by Django 5.1 on 2024-12-28 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_merge_20241228_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created_by_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_records', to='record.scheduledrecord'),
        ),
    ]
