# Generated by Django 5.1 on 2025-01-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_record_created_by_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledrecord',
            name='celery_task_id',
        ),
    ]
