# Generated by Django 5.1 on 2024-09-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_accountstatus_account_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(blank=True, default='anonymous', max_length=100, null=True),
        ),
    ]
