# Generated by Django 5.1 on 2024-09-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_account_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_date',
        ),
    ]
