# Generated by Django 5.1 on 2024-10-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_account_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(default='unverified', max_length=20),
        ),
    ]
